### PR TITLE
Replace incorrect path in focus function

### PR DESCRIPTION
**Pull request by niladam**
This replaces the incorrect path (probably while developing) `~/workspace/chrome-control/chrome.js` with the one included (`./chrome.js`) in the workflow, so that it allows the focus functionality to work.

The change was done in Alfred, and the result was exported replacing `Chrome Control.alfredworkflow`.

### CODE REVIEW

**Comment by niladam** [comment]
Oh. And i somehow forgot to totally remind myself to **thank you** for both the script and the workflow. It'll improve my productivity too!:)

**Comment by niladam** [comment]
Also, as a sidenote - i would make sure to enable issues -- as that was my initial direction but i couldn't make one so i made the small change myself :)

**Comment by bit2pixel** [comment]
Hi Madalin, 

I will be only accepting pull requests only to the source code, but I've added your fix to the workflow and updated the release. Also appended you to the `CONTRIBUTORS.md` and made sure to give you credit in the commit message.

I've also enabled issues; thanks for the recommendation! Feel free to create one for this issue and I'd be happy to resolve it there.

Thank you so much for fixing this and thank you for your kind words! 

Happy Monday,

Renan

**Comment by niladam** [comment]
@bit2pixel that's fine. I thought so. I don't like compiled code as well (not to mention safety here!), -- that's why i explained exactly what i did so that you can make the required changes yourself :)

I had to fork and send the PR because there was no other way of letting you know. 

Thank you for opening the issues, i'll make sure to use them if needed :)

Happy Monday to you too! - And thank you for adding me to the contributors file -- but it was just a minor fix :)

**Pull request closed without merging**
